name: nuntium
description: A News Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  flutter_svg: 
  get_it: ^7.6.0
  get: ^4.6.5
  shared_preferences: ^2.1.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.1
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  internet_connection_checker_plus: ^1.0.1
  firebase_core: ^2.14.0
  flutter_local_notifications: ^14.1.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  firebase_auth: ^4.6.3
  pinput: ^2.2.31
  cloud_firestore: ^4.8.2
  webview_flutter: ^4.2.2
  persistent_bottom_nav_bar_v2: ^4.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/vectors/



  fonts:
    - family: SP_Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
